import './globals.css'
import Navbar from './Comp/Navbar'
import NavbarHero from './Comp/NavbarHero'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <NavbarHero />
        {children}
      </body>
    </html>
  )
}
